/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 sacchetto_avana.glb 
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'
import { Mesh, MeshStandardMaterial, RepeatWrapping, Texture, Vector2 } from 'three'

type Props = {
  textureFront: Texture,
  textureBack: Texture, 
  textureSide: Texture | undefined, 
}

export function Model(props: Props) {
  const { textureFront, textureBack, textureSide } = props

  const { nodes, materials } = useGLTF('models/sacchetto_avana.glb')
  const defaultMaterial = materials.Plastica5.clone() as MeshStandardMaterial
  const texturedMaterialFront = defaultMaterial.clone()
  const texturedMaterialBack = defaultMaterial.clone()
  const texturedMaterialSide = defaultMaterial.clone()

  if (textureFront) {
    textureFront.center = new Vector2(0.5, 0.5)
    texturedMaterialFront.map = textureFront.clone()
    texturedMaterialFront.map.needsUpdate = true
    texturedMaterialFront.map.rotation = Math.PI / 2
  }

  if (textureBack) {
    textureBack.center = new Vector2(0.5, 0.5)
    texturedMaterialBack.map = textureBack.clone()
    texturedMaterialBack.map.needsUpdate = true
    texturedMaterialBack.map.rotation = Math.PI / 1
    texturedMaterialBack.map.wrapS = RepeatWrapping
    texturedMaterialBack.map.repeat.x = - 1
  }

  if (textureSide) {
    textureSide.center = new Vector2(0.5, 0.5)
    texturedMaterialSide.map = textureSide.clone()
    texturedMaterialSide.map.needsUpdate = true
    texturedMaterialSide.map.rotation = - Math.PI / 2
    texturedMaterialSide.map.wrapS = RepeatWrapping
    texturedMaterialSide.map.repeat.x = - 1
  }


  const ref = useRef()
  useFrame((state, delta) => ref.current ? ref.current.rotation.y += delta : {})

  return (
    <group dispose={null} ref={ref}>
      <group position={[17, -4, -8]} rotation={[Math.PI / 2, 0, 0]} scale={0.187}>
        <mesh geometry={(nodes.sacchetto_diviso_interno_1 as Mesh).geometry} material={defaultMaterial} />

        {/* left */}
        <mesh geometry={(nodes.sacchetto_diviso_interno_2 as Mesh).geometry} material={texturedMaterialSide} />

        {/* front */}
        <mesh geometry={(nodes.sacchetto_diviso_interno_3 as Mesh).geometry} material={texturedMaterialFront} />

        {/* right */}
        <mesh geometry={(nodes.sacchetto_diviso_interno_4 as Mesh).geometry} material={texturedMaterialSide} />

        {/* back */}
        <mesh geometry={(nodes.sacchetto_diviso_interno_5 as Mesh).geometry} material={texturedMaterialBack} />
      </group>
    </group>
  )
}

useGLTF.preload('models/sacchetto_avana.glb')
