/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 sacchetto_avana.glb 
*/

import { useGLTF } from '@react-three/drei'
import { RepeatWrapping, Vector2 } from 'three'

export function Model(props) {
  const {textureFront, textureBack } = props
  if (!textureFront && !textureBack) return

  const {nodes, materials } = useGLTF('models/sacchetto_avana.glb')
  const defaultMaterial = materials.Plastica5.clone()
  const texturedMaterialSide = defaultMaterial.clone()
  const texturedMaterialFront = defaultMaterial.clone()
  const texturedMaterialBack = defaultMaterial.clone()

  if (textureFront) textureFront.center = new Vector2(0.5, 0.5)
  if (textureBack) textureBack.center = new Vector2(0.5, 0.5)

  texturedMaterialSide.map = textureFront ? textureFront.clone() : textureBack.clone()
  texturedMaterialSide.map.needsUpdate = true
  texturedMaterialSide.map.rotation = - Math.PI / 2
  texturedMaterialSide.map.wrapS = RepeatWrapping
  texturedMaterialSide.map.repeat.x = - 1

  texturedMaterialFront.map = textureFront.clone() || textureBack.clone()
  texturedMaterialFront.map.needsUpdate = true
  texturedMaterialFront.map.rotation = Math.PI / 2

  texturedMaterialBack.map = textureBack.clone() || textureFront.clone()
  texturedMaterialBack.map.needsUpdate = true
  texturedMaterialBack.map.rotation = Math.PI / 1
  texturedMaterialBack.map.wrapS = RepeatWrapping
  texturedMaterialBack.map.repeat.x = - 1

  return (
    <group {...props} dispose={null}>
      <group position={[17, -4, -8]} rotation={[Math.PI / 2, 0, 0]} scale={0.187}>
        <mesh geometry={nodes.sacchetto_diviso_interno_1.geometry} material={defaultMaterial} />

        {/* left */}
        <mesh geometry={nodes.sacchetto_diviso_interno_2.geometry} material={texturedMaterialSide} />

        {/* front */}
        <mesh geometry={nodes.sacchetto_diviso_interno_3.geometry} material={texturedMaterialFront} />

        {/* right */}
        <mesh geometry={nodes.sacchetto_diviso_interno_4.geometry} material={texturedMaterialSide} />

        {/* back */}
        <mesh geometry={nodes.sacchetto_diviso_interno_5.geometry} material={texturedMaterialBack} />
      </group>
    </group>
  )
}

useGLTF.preload('models/sacchetto_avana.glb')
