/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/sacchetto_bianco.glb --transform 
Files: public/models/sacchetto_bianco.glb [973.48KB] > /Users/danielerapisarda/projects/pack-config/sacchetto_bianco-transformed.glb [94.28KB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('model/sacchetto_bianco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sacchetto_diviso_interno.geometry} material={materials.Plastica5} position={[16.709, -3.767, -7.891]} rotation={[Math.PI / 2, 0, 0]} scale={0.187} />
    </group>
  )
}

useGLTF.preload('/sacchetto_bianco-transformed.glb')
